### ISSUE TITLE
Please plan a release

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify-kafka#104]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

@GaryWilber  fixed the regression rdkafka and now the latest version of rdkafka passes the tests like a charm

see:
https://github.com/Blizzard/node-rdkafka/issues/1016
#103 

We should plan a release to provide the latest version.

**Comment by Eomm** [comment]
https://github.com/fastify/fastify-kafka/releases/tag/v2.2.1

**Comment by Uzlopak** [comment]
Thank you
