### ISSUE TITLE
use kafka-node to replace node-rdkafka

### ISSUE THREAD

**Issue by marswong** [fastify/fastify-kafka#29]
## 🚀 Feature Proposal

[kafka-node](https://github.com/SOHU-Co/kafka-node) is a portable implementation and easy to go. It'd been a hard work to maintain a dependency built on OpenSSL, so does [node-rdkafka](https://github.com/Blizzard/node-rdkafka).

## Example

The API of `fastify-kafka` could be the same and the only break change might be the configuration of `producer` and `consumer`, 'caz there is a little difference on `sasl` implementation between `kafka-node` and `node-rdkfaka`.

**Comment by zekth** [comment]
kafka-node is an abandonned project see: https://github.com/SOHU-Co/kafka-node/issues/1445
